# Generated by Django 5.2.15 on 2026-09-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.PositiveIntegerField()),
                ('tipo', models.CharField(choices=[('NI', 'Niños'), ('ES', 'Estándar'), ('VIP', 'VIP')], default='ES', max_length=50)),
            ],
        ),
    ]
